[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
solc = "0.8.20"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
